MGI_GAF:
  url: ftp.ebi.ac.uk/pub/databases/GO/goa/MOUSE/goa_mouse.gaf.gz
MGI_GPI:
  url: http://snapshot.geneontology.org/annotations/mgi.gpi.gz
ORTHO:
  url: https://fms.alliancegenome.org/download/ORTHOLOGY-ALLIANCE-JSON_COMBINED.json.gz
RGD:
  url: http://snapshot.geneontology.org/annotations/rgd.gaf.gz
